name: windows

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".github/workflows/gen_windows.yml"
      - "assets/fonts/**/*"
      - "assets/icon/*"
      - "assets/windows/**/*"
      - "ci/deploy.sh"
      - "ci/windows-installer.iss"

jobs:
  build:
    runs-on: "windows-latest"
    
    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      RUSTUP_WINDOWS_PATH_ADD_BIN: "1"

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust for x86_64"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "x86_64-pc-windows-msvc"
      - name: "Install Rust for aarch64"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "aarch64-pc-windows-msvc"
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.5
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependencies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Build wezterm for x86_64 (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm --release --target x86_64-pc-windows-msvc
      - name: "Build wezterm for aarch64 (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm --release --target aarch64-pc-windows-msvc
      - name: "Build wezterm-gui for x86_64 (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm-gui --release --target x86_64-pc-windows-msvc
      - name: "Build wezterm-gui for aarch64 (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm-gui --release --target aarch64-pc-windows-msvc
      - name: "Build wezterm-mux-server for x86_64 (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm-mux-server --release --target x86_64-pc-windows-msvc
      - name: "Build wezterm-mux-server for aarch64 (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm-mux-server --release --target aarch64-pc-windows-msvc
      - name: "Build strip-ansi-escapes for x86_64 (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p strip-ansi-escapes --release --target x86_64-pc-windows-msvc
      - name: "Build strip-ansi-escapes for aarch64 (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p strip-ansi-escapes --release --target aarch64-pc-windows-msvc
      - name: "Install cargo-nextest from Cargo"
        uses: baptiste0928/cargo-install@v3
        with:
          crate: "cargo-nextest"
          cache-key: "windows"
      - name: "Test"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo nextest run --all --no-fail-fast --target x86_64-pc-windows-msvc
          cargo nextest run --all --no-fail-fast --target aarch64-pc-windows-msvc
      - name: "Package"
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "windows"
          path: |
            WezTerm-*.zip
            WezTerm-*.exe
